import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

import HomePage from '../src/components/home/home-page';

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data} />
    </div>
  )
}

export async function getServerSideProps() {
  const {events_categories} = await import('/data/data.json');

  //const res = await fetch('URL)
  //const data = await res.json('')

  // console.log(events_categories)
  return {
    props: {
      data: events_categories,
    },
  };
}
